---
title: "Supplementals for Parent-Child Adaptive Response to Emerging Digital Ecologies"
output: html_document
author: "Hollie Abele"
---

Download supplemental_data.RData to run.

```{r load supplemental_data, include=FALSE}
load("supplemental_data.RData")
```

## T-test

```{r, echo=FALSE}
library(tidyverse)
library(stats)
```

```{r}
ttest_female <- ttest |>
  filter(`Your.gender`== 'Female')

ttest_male <- ttest |>
  filter(`Your.gender` == 'Male')
```

```{r}
t.test(ttest_male$`Numeric.controls`, ttest_female$`Numeric.controls`)
```

## Bayes factor

```{r, echo=FALSE}
library(BayesFactor)
```

```{r}
coplot(parental_controls ~ income | gender, data = combined_correlation_columns, panel = panel.smooth,
       xlab = "income", ylab = "parental controls")
```

```{r}
coplot(parental_controls ~ education | gender, data = combined_correlation_columns, panel = panel.smooth,
       xlab = "education", ylab = "parental controls")
```

```{r}
combined_correlation_income <- combined_correlation_columns

combined_correlation_income$income = factor(combined_correlation_income$income)
levels(combined_correlation_income$income) = c("One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")

summary(aov(parental_controls ~ gender*income, data=combined_correlation_income))
```

```{r}
combined_correlation_education <- combined_correlation_columns

combined_correlation_education$education = factor(combined_correlation_education$education)
levels(combined_correlation_education$education) = c("One", "Two", "Three", "Four", "Five", "Six")

summary(aov(parental_controls ~ gender*education, data=combined_correlation_education))
```

## Two-mode network

```{r, echo=FALSE}
library(ggplot2)
library(ggraph)
library(shadowtext)
library(igraph)
library(ggforce)
```

```{r}
transformedmatrix<- t(combined_matrix)

transformedmatrix[transformedmatrix<=20] <- 0
transformedmatrix[transformedmatrix>=21 & transformedmatrix<=100] <- 1
transformedmatrix[transformedmatrix>=101 & transformedmatrix<=200] <- 2

as.matrix(transformedmatrix)
```

```{r}
g <- graph_from_biadjacency_matrix(transformedmatrix, mode="all", weighted=TRUE)
```

```{r}
TotalCountmatrix <- combined_matrix %>% 
  colSums(combined_matrix, )

TotalRowmatrix <- combined_matrix %>% 
  rowSums(combined_matrix, )

rowsumsscaled <- TotalRowmatrix
colsumscaled <- TotalCountmatrix

nodesizes <- c(539, 527, 649, 442, 209, 384, 586, 635, 251, 704, 803, 188, 837, 627, 327, 1366, 778)

palette <- c("red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "darkblue","darkblue", "darkblue", "darkblue", "darkblue", "darkblue", "darkblue")

```

```{r}
ggraph(g, layout = "centrality", cent = strength(g)) +
  geom_edge_link0(aes(edge_linewidth = weight), edge_colour = "grey66") +
  geom_node_point(aes(fill = palette, size = nodesizes), shape = 21) +
  shadowtext::geom_shadowtext(aes(x, y, label = name), color = "black", size = 3.17, bg.colour = "white") +
  scale_edge_width_continuous(range = c(0.3, 1.5)) +
  scale_size_continuous(range = c(5, 18)) +
  scale_fill_manual(values = c("red","darkblue")) +
  coord_cartesian(xlim = c(-115,115), ylim = c(-90,90))+
  theme_graph() +
  theme(legend.position = "none")
```

# References

https://cran.r-project.org/web/packages/BayesFactor/vignettes/manual.html

https://schochastics.github.io/netVizR/
